crates:
  default:
    display:
      material: "TRIPWIRE_HOOK"
      data: 0
      name: "&7Key Default"
      lore:
        - "&7Use this crate to open"
        - "&7and earn rewards"
      glow: false
    rewards:
      1:
        material: "DIAMOND_BLOCK"
        data: 0
        amount: 32
        glow: false
        command: "none"
        chance: 0.02
        rarity: "legendary"
      2:
        material: "IRON_BLOCK"
        data: 0
        amount: 32
        name: "&eIron Block"
        lore:
          - "&7a nice block"
        glow: false
        command: "none"
        enchants:
          - "DAMAGE_ALL:10"
        chance: 0.1
        rarity: "uncommon"
      3:
        material: "GOLD_BLOCK"
        data: 0
        amount: 1
        glow: false
        command: "give {player} gold_block 64"
        chance: 0.3
        rarity: "common"